server.port=8090

# PostgreSQL Database Connection
spring.application.name=fridge-manager-api
spring.datasource.url=jdbc:postgresql://localhost:5432/fridge_manager
spring.datasource.username=harsh
spring.datasource.password=harsh

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update

# Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Explicity set the PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Application Logging Configurations
logging.file.name=logs/fridge-manager.log
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.fridgeapp=DEBUG